### PR TITLE
added disable tests flag to docker build scripts

### PR DESCRIPTION
**Pull request by nareshkumarthota**
This PR fixes issue #104 

Added `--disable-tests` flag to disable unit tests execution.

### CODE REVIEW

**Review by rameshpolishetti — APPROVED** [review]
Looks good to me

**Comment by rameshpolishetti** [comment]
Adding @ykalidin to validate this.

**Comment by ykalidin** [comment]
Working as expected

**Comment by tsaxena18** [comment]
From chore-cloud-testing branch, verified application build script from docker/bin, frominstall and s2i and the flag for disabling unit tests is working fine.
Worked with and without disabling tests and application images are built and run successfully via docker run. No issue.
Attached build log for all cases.
[buildLog-pr105.txt](https://github.com/TIBCOSoftware/be-tools/files/5181948/buildLog-pr105.txt)

**Pull request merged**
