### PR TITLE
Feature cloud enhancements

### PR DESCRIPTION
**Pull request by rameshpolishetti**
This PR contains:

## Enhancements:
* #71 Add docker support for new deployment configurations added in TIBCO BE 6.0.0
* #59 Add support for helm charts
* Docker unit tests: Validates BE app image structure and metadata
* Helm unit tests: Validates helm chart templates & deployments

## Bug Fixes:
* #74 Engines defaults to tibpgm protocol, even if AS_DISCOVER_URL is specified in run command
* #67 Be application throwing waiting for space error in k8s deployments
* #54 Keep specific tag version for base OS images instead of using 'latest'.
* #43 Incorrect error message in case of wrong installers are present at installer location while building image

### CODE REVIEW

**Comment by vpatil-tibco** [comment]
@vilasshelar - Waiting for you to provide an update on validation front, so that we can go ahead and merge the changes.

**Comment by tsaxena18** [comment]
@vpatil-tibco @rameshpolishetti @vilasshelar 
I did validation for helm with AS2 on Azure platform and tried all the basic use cases - InMemory, Cache and all Persistence options (None, SN, Store).
Initially I found some minor issues which I had already raised and it got fixed as I observed.
All the above cases went fine, except the **Store** option which I tried several times with MySql but the k8's pods are crashing with below error :
2020 Aug 07 13:55:47.926 GMT Z fdsa600app-becacheagent-0 FATAL [main] - [jdbcstore] JdbcStore initialization failed.
java.lang.Exception: database type in sharedresource [ Berkeley DB ] does not match with type in cdd [ MySQL ]
        at com.tibco.be.jdbcstore.impl.DBManager.init(DBManager.java:157)
        at com.tibco.be.jdbcstore.JdbcStore.initialize(JdbcStore.java:588)
        at com.tibco.be.jdbcstore.JdbcStore.<init>(JdbcStore.java:240)
        at com.tibco.cep.runtime.service.dao.impl.tibas.backingstore.BEDataGridJdbcStore.<init>(SourceFile:60)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.tibco.cep.runtime.service.dao.impl.tibas.ASDaoProvider.if(SourceFile:658)
        at com.tibco.cep.runtime.service.dao.impl.tibas.ASDaoProvider.initHook(SourceFile:417)
        at com.tibco.cep.runtime.service.om.impl.AbstractDaoProvider.init(AbstractDaoProvider.java:83)
        at com.tibco.cep.runtime.service.cluster.MultiAgentCluster.init(MultiAgentCluster.java:166)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:840)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:319)
        at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:167)
        at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)

We have removed Berkeley DB in BE 6.0.0 so it should not have come.

Attached logs and deployment files for the reference.
[cacheagent.txt](https://github.com/TIBCOSoftware/be-tools/files/5041874/cacheagent.txt)

**Comment by rameshpolishetti** [comment]
@tsaxena18 thank you for your time. Looks like - "Blank default value for database_driver GLOBAL VARIABLE is causing the issue"
Please update the project accordingly, generate cdd/ear again, and try.

**Comment by tsaxena18** [comment]
@vpatil-tibco @rameshpolishetti 
The backing store case is working fine after providing value to the global variable of jdbc driver. With this all basic use cases with AS2 are covered now.
Attached logs for store case for the reference.
[logs.zip](https://github.com/TIBCOSoftware/be-tools/files/5042918/logs.zip)

**Pull request merged**
