### PR TITLE
Fix for issue #73

### PR DESCRIPTION
**Pull request by CloudDevBe**
Fix for #73

### CODE REVIEW

**Comment by vpatil-tibco** [comment]
@vilasshelar - Verify this issue on the BEHFfix branch. Once done, add your comments, accordingly we'll merge in master.

**Comment by tsaxena18** [comment]
With BEHFfix branch, I am able to build BE app image with and without using BE Hotfix successfully on Linux. 
Created docker images for in-memory as well as cache based projects and then ran the application via docker which went fine.
Noticeable change was app size which increases from 660 mb (without HF) to 1 gb (with HF). I have used [AS + BE Enterprise + Process + Views + HF].

I tried the BE RMS script as well but it seems like the fix is present for app script only as RMS shows the BE 5.6.1 GA version.
Attached log for the reference. 
[Logs-BEHFfix.zip](https://github.com/TIBCOSoftware/be-tools/files/4885656/Logs-BEHFfix.zip)

**Comment by vpatil-tibco** [comment]
@tsaxena18 Did the size changes happen before or something you are seeing right now?

**Comment by tsaxena18** [comment]
@vpatil-tibco  The size difference in this case is much larger than what we had seen earlier, especially for linux images. Given that the size of BE 5.6.1 HF4 itself is 216 mb, the increase in size is more.

**Comment by skbasit** [comment]
The difference in size is because when we install HF we keep a backup of previous artifacts, in case of this particular HF it is whole jre. That being said, fix would be to skip this backup from going in the final image.

**Comment by vpatil-tibco** [comment]
That's right, we included a JRE change in this one. Sure, makes sense for the size change.

@CloudDevBe - Update the fix for RMS and update the scripts to prevent including this backup.

**Comment by vpatil-tibco** [comment]
@tsaxena18 Over to you.

**Comment by tsaxena18** [comment]
I am able to build BE app and RMS image with and without using BE Hotfix successfully on Linux.
Also tried to building the app and RMS images with BE Hotfix and without one of the BE add-on, which also went fine.
For every case mentioned, created docker images for in-memory, cache based project and RMS. Then ran the application via docker which went fine. The BE version is correct in all cases.
The docker size for BE app has also been fixed. Now there is a minor difference (2 mb) between the images with and without BE Hotfix. 

I am not sure if the fix is applicable to TEA script as well. But I tried to build TEA image and it is failing with and without HF. 
Should I raise the ticket for TEA ?
Attached all the log for the reference.
[Logs-BEHFfix-1.zip](https://github.com/TIBCOSoftware/be-tools/files/4890476/Logs-BEHFfix-1.zip)

**Comment by vpatil-tibco** [comment]
Yes, raise a separate one for TEA.

**Pull request merged**
