### PR TITLE
Fix dockertest issues

### PR DESCRIPTION
**Pull request by LakshmiMekala**
This PR Addresses fix for below issues. #119 #122 
Update containter structure test docker image to fixed version v1.9.1
Skip docker tests when docker context not pointing to local docker daemon

### CODE REVIEW

**Review by rameshpolishetti — APPROVED** [review]
Looks good to me

**Comment by rameshpolishetti** [comment]
This PR fixes issue #119 & #122 . Adding @tsaxena18 to validate this.

**Comment by nareshkumarthota** [comment]
This PR updated with fixes issue #121 .

**Review by rameshpolishetti — APPROVED** [review]
LGTM

**Comment by tsaxena18** [comment]
Confirmed, the fix are fine.

**Pull request merged**
