### PR TITLE
added imagepullsecret name provision

### PR DESCRIPTION
**Pull request by nareshkumarthota**
This PR fixes issue #103

### CODE REVIEW

**Review by rameshpolishetti — APPROVED** [review]
LGTM

**Comment by rameshpolishetti** [comment]
Adding @jgirase to help to validate the PR.

**Comment by rameshpolishetti** [comment]
Adding @jgirase to help to validate the PR.

**Comment by rameshpolishetti** [comment]
Adding @jgirase to help to validate the PR.

**Comment by jgirase-tibco** [comment]
Its working after specifying pullsecret value for field imagepullsecret: in values.yaml for helm.

**Pull request merged**
