### PR TITLE
fix errors in minikube deployment files for inmemory and cache types

### PR DESCRIPTION
**Pull request by LakshmiMekala**
This PR contains fix for deployment errors for minikube -> inmemory and cache modes.

### CODE REVIEW

**Comment by vpatil-tibco** [comment]
@dijadhav - Can you check this?

**Comment by vivekshende** [comment]
> @dijadhav - Can you check this?

@tsaxena18 What version of minikube did we test it on earlier? It seems this api is no longer supported.
It looks this API was removed in k8s v1.16 https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by tsaxena18** [comment]
@vivekshende We did the deployment with K8's version 1.14.

**Comment by LakshmiMekala** [comment]
@tsaxena18 whats the kubectl version?

**Comment by tsaxena18** [comment]
@LakshmiMekala kubectl version used was 1.14.

**Pull request merged**
