### PR TITLE
Chore teagent scripts

### PR DESCRIPTION
**Pull request by nareshkumarthota**
This PR contains fix for teagent image.

### CODE REVIEW

**Comment by shivgangat** [comment]
Working as expected with updated scripts.

**Review by dijadhav — APPROVED** [review]
Changes are ok. Please test it with aws and fargate also. Also there is some code duplicate in aws and fargate scripts you can combine that in single file.

**Comment by shivgangat** [comment]
Verified with AWS Fargate too and it's working fine.

**Review by rameshpolishetti — APPROVED** [review]
Looks good to me.

**Comment by rameshpolishetti** [comment]
@nareshkumarthota merging the PR with a note - there will be another PR to address the issue #220 and incorporate @dijadhav comments.

**Pull request merged**
