### PR TITLE
updating values.yaml beservice type information

### PR DESCRIPTION
**Pull request by ykalidin**

### CODE REVIEW

**Comment by ykalidin** [comment]
@jgirase Please validate the Change

**Review by rameshpolishetti — APPROVED** [review]
LGTM

**Comment by rameshpolishetti** [comment]
Adding @tsaxena18 as well to validate this PR.

**Comment by jgirase-tibco** [comment]
Its LoadBalancer type for beservice in values.yml and it works fine.

**Comment by tsaxena18** [comment]
Looks fine to me.

**Pull request merged**
