### PR TITLE
Feature config provider

### PR DESCRIPTION
**Pull request by nareshkumarthota**

### CODE REVIEW

**Comment by ykalidin** [comment]
Working fine. Verified with http,consul and conjur config providers.

**Comment by rameshpolishetti** [comment]
@ykalidin please validate windows-linux container & windows-windows containers cases as well.

**Comment by ykalidin** [comment]
Working fine.
Verified http,consul,aws and conjur config providers in linux.
http and consul gvproviders in windows-linux and windows-windows containers.

**Review by rameshpolishetti — APPROVED** [review]
Looks good to me

**Pull request merged**
